import {
  pgTable,
  uuid,
  varchar,
  text,
  boolean,
  numeric,
  integer,
  smallint,
  bigint,
  jsonb,
  date,
  index,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { timestamptz } from '../columns.js';
import { organizations } from './organizations.js';
import { customer_groups, price_tiers } from './master.js';

export const customers = pgTable(
  'customers',
  {
    id: uuid('id').primaryKey(),
    org_id: uuid('org_id').notNull().references(() => organizations.id),
    customer_code: varchar('customer_code', { length: 20 }).notNull(),
    salutation: varchar('salutation', { length: 10 }),
    name: varchar('name', { length: 120 }).notNull(),
    display_name: varchar('display_name', { length: 120 }),
    type: varchar('type', { length: 20 }).notNull().default('Individual'),
    phone: varchar('phone', { length: 15 }).notNull(),
    alt_phone: varchar('alt_phone', { length: 15 }),
    email: varchar('email', { length: 120 }),
    whatsapp_number: varchar('whatsapp_number', { length: 15 }),
    gstin: varchar('gstin', { length: 15 }),
    gst_reg_type: varchar('gst_reg_type', { length: 30 }).notNull().default('Consumer'),
    pan: varchar('pan', { length: 10 }),
    place_of_supply: varchar('place_of_supply', { length: 2 }),
    billing_address: jsonb('billing_address'),
    shipping_address: jsonb('shipping_address'),
    shipping_same_as_billing: boolean('shipping_same_as_billing').notNull().default(true),
    credit_limit: numeric('credit_limit', { precision: 14, scale: 2 }).notNull().default('0'),
    credit_days: integer('credit_days').notNull().default(0),
    block_on_limit_breach: boolean('block_on_limit_breach').notNull().default(false),
    block_on_overdue: boolean('block_on_overdue').notNull().default(false),
    customer_group_id: uuid('customer_group_id').references(() => customer_groups.id),
    price_tier_id: uuid('price_tier_id').references(() => price_tiers.id),
    opening_balance: numeric('opening_balance', { precision: 14, scale: 2 }).notNull().default('0'),
    opening_as_of_date: date('opening_as_of_date'),
    status: varchar('status', { length: 20 }).notNull().default('Active'),
    tags: text('tags').array().default(sql`'{}'::text[]`),
    custom_fields: jsonb('custom_fields').default({}),
    created_at: timestamptz('created_at').notNull().default(sql`now()`),
    created_by: uuid('created_by').notNull(),
    updated_at: timestamptz('updated_at').notNull().default(sql`now()`),
    updated_by: uuid('updated_by').notNull(),
    deleted_at: timestamptz('deleted_at'),
    deleted_by: uuid('deleted_by'),
    row_version: bigint('row_version', { mode: 'number' }).notNull().default(1),
    sync_status: smallint('sync_status').notNull().default(0),
  },
  (table) => [
    index('customers_org_id_idx').on(table.org_id),
    index('customers_org_phone_idx').on(table.org_id, table.phone),
    index('customers_org_status_idx').on(table.org_id, table.status),
  ],
);

export const vendors = pgTable(
  'vendors',
  {
    id: uuid('id').primaryKey(),
    org_id: uuid('org_id').notNull().references(() => organizations.id),
    vendor_code: varchar('vendor_code', { length: 20 }).notNull(),
    name: varchar('name', { length: 120 }).notNull(),
    type: varchar('type', { length: 20 }).notNull().default('Business'),
    phone: varchar('phone', { length: 15 }),
    email: varchar('email', { length: 120 }),
    gstin: varchar('gstin', { length: 15 }),
    pan: varchar('pan', { length: 10 }),
    billing_address: jsonb('billing_address'),
    bank_account_no: varchar('bank_account_no', { length: 30 }),
    bank_ifsc: varchar('bank_ifsc', { length: 15 }),
    bank_name: varchar('bank_name', { length: 80 }),
    upi_id: varchar('upi_id', { length: 80 }),
    credit_days: integer('credit_days').notNull().default(0),
    opening_balance: numeric('opening_balance', { precision: 14, scale: 2 }).notNull().default('0'),
    opening_as_of_date: date('opening_as_of_date'),
    status: varchar('status', { length: 20 }).notNull().default('Active'),
    custom_fields: jsonb('custom_fields').default({}),
    created_at: timestamptz('created_at').notNull().default(sql`now()`),
    created_by: uuid('created_by').notNull(),
    updated_at: timestamptz('updated_at').notNull().default(sql`now()`),
    updated_by: uuid('updated_by').notNull(),
    deleted_at: timestamptz('deleted_at'),
    deleted_by: uuid('deleted_by'),
    row_version: bigint('row_version', { mode: 'number' }).notNull().default(1),
    sync_status: smallint('sync_status').notNull().default(0),
  },
  (table) => [
    index('vendors_org_id_idx').on(table.org_id),
    index('vendors_org_name_idx').on(table.org_id, table.name),
  ],
);
